#pragma once
#include "stdafx.h"
#include "Common/GameConfig.hpp"

#include "GameConfig/IConfigManager.h"
#include "GameConfig/IGameConfigManager.h"
#include "GameConfig/ConfigManger/DefaultGameConfigManager.h"

#include "GameConfig/ConfigManger/IAction.h"
#include "GameConfig/ConfigManger/Actions/BrowseFile.h"
#include "GameConfig/ConfigManger/Actions/BrowseFolder.h"
#include "GameConfig/ConfigManger/Actions/PickColor.h"

#include "GameConfig/ConfigManger/ISource.h"
#include "GameConfig/ConfigManger/IFileSource.h"
#include "GameConfig/ConfigManger/Sources/NullSource.h"
#include "GameConfig/ConfigManger/Sources/INISource.h"
#include "GameConfig/ConfigManger/Sources/XMLSource.h"
#include "GameConfig/ConfigManger/Sources/XMLRefSource.h"
#include "GameConfig/ConfigManger/Sources/XMLFileSource.h"

#include "GameConfig/ConfigManger/Item.h"
#include "GameConfig/ConfigManger/IViewItem.h"
#include "GameConfig/ConfigManger/Items/CategoryItem.h"
#include "GameConfig/ConfigManger/Items/SimpleItem.h"
#include "GameConfig/ConfigManger/Items/StructItem.h"
#include "GameConfig/ConfigManger/Items/StructSubItem.h"

#include "GameConfig/ConfigManger/ISamplingFunction.h"
#include "GameConfig/ConfigManger/SamplingFunctions/Generic.h"
#include "GameConfig/ConfigManger/SamplingFunctions/FindFiles.h"
#include "GameConfig/ConfigManger/SamplingFunctions/GetAvailableTranslations.h"
#include "GameConfig/ConfigManger/SamplingFunctions/GetStartupWorkspaces.h"
#include "GameConfig/ConfigManger/SamplingFunctions/GetVideoAdapters.h"
#include "GameConfig/ConfigManger/SamplingFunctions/GetVideoModes.h"
#include "GameConfig/ConfigManger/SamplingFunctions/GetVirtualKeys.h"

#include "GameConfig/ConfigManger/DataType.h"
#include "GameConfig/ConfigManger/Definition.h"
#include "GameConfig/ConfigManger/ItemGroup.h"
#include "GameConfig/ConfigManger/ItemOptions.h"
#include "GameConfig/ConfigManger/ItemSamples.h"
#include "GameConfig/ConfigManger/ItemValue.h"
#include "GameConfig/ConfigManger/ITypeDetector.h"

#include "GameConfig/ConfigManger/DisplayModel.h"
#include "GameConfig/ConfigManger/Workspace.h"
#include "GameConfig/ConfigManger/WorkspaceController.h"
